### ISSUE TITLE
django.db.utils.ProgrammingError: (1146, "Table 'hunan_web.warehouse_spiderlog' doesn't exist")

### ISSUE THREAD

**Issue by shoukewei** [ChenZixinn/scenery_spider_web#1]
I run the server and meet the following error, but I could not solve it. Could you give a help. Thank you!

```
S D:\scenery_spider_web> python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "d:\scenery_spider_web\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "d:\scenery_spider_web\env\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "d:\scenery_spider_web\env\lib\site-packages\pymysql\cursors.py", line 158, in execute
    result = self._query(query)
  File "d:\scenery_spider_web\env\lib\site-packages\pymysql\cursors.py", line 325, in _query
    conn.query(q)
  File "d:\scenery_spider_web\env\lib\site-packages\pymysql\connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "d:\scenery_spider_web\env\lib\site-packages\pymysql\connections.py", line 779, in _read_query_result
    result.read()
  File "d:\scenery_spider_web\env\lib\site-packages\pymysql\connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "d:\scenery_spider_web\env\lib\site-packages\pymysql\connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "d:\scenery_spider_web\env\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "d:\scenery_spider_web\env\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'hunan_web.warehouse_spiderlog' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\scenery_spider_web\env\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "d:\scenery_spider_web\env\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "d:\scenery_spider_web\env\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "d:\scenery_spider_web\env\lib\site-packages\django\core\management\commands\runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "d:\scenery_spider_web\env\lib\site-packages\django\core\management\base.py", line 487, in check
    all_issues = checks.run_checks(
  File "d:\scenery_spider_web\env\lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "d:\scenery_spider_web\env\lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "d:\scenery_spider_web\env\lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    return check_method()
  File "d:\scenery_spider_web\env\lib\site-packages\django\urls\resolvers.py", line 480, in check
    for pattern in self.url_patterns:
  File "d:\scenery_spider_web\env\lib\site-packages\django\utils\functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "d:\scenery_spider_web\env\lib\site-packages\django\urls\resolvers.py", line 696, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "d:\scenery_spider_web\env\lib\site-packages\django\utils\functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "d:\scenery_spider_web\env\lib\site-packages\django\urls\resolvers.py", line 689, in urlconf_module
    return import_module(self.urlconf_name)
  File "d:\scenery_spider_web\env\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\scenery_spider_web\hunan_web\urls.py", line 19, in <module>
    from mainapp import views
  File "D:\scenery_spider_web\mainapp\views.py", line 12, in <module>
    all_map = AllMap()
  File "D:\scenery_spider_web\mainapp\utils\all_map.py", line 35, in __init__
    self.spider_time = timezone.localtime(SpiderLog.objects.last().spider_time).strftime('%Y-%m-%d %H:%M:%S')
  File "d:\scenery_spider_web\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "d:\scenery_spider_web\env\lib\site-packages\django\db\models\query.py", line 758, in last
    for obj in (self.reverse() if self.ordered else self.order_by("-pk"))[:1]:
  File "d:\scenery_spider_web\env\lib\site-packages\django\db\models\query.py", line 320, in __iter__
    self._fetch_all()
  File "d:\scenery_spider_web\env\lib\site-packages\django\db\models\query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "d:\scenery_spider_web\env\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "d:\scenery_spider_web\env\lib\site-packages\django\db\models\sql\compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "d:\scenery_spider_web\env\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "d:\scenery_spider_web\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "d:\scenery_spider_web\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "d:\scenery_spider_web\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "d:\scenery_spider_web\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "d:\scenery_spider_web\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "d:\scenery_spider_web\env\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "d:\scenery_spider_web\env\lib\site-packages\pymysql\cursors.py", line 158, in execute
    result = self._query(query)
  File "d:\scenery_spider_web\env\lib\site-packages\pymysql\cursors.py", line 325, in _query
    conn.query(q)
  File "d:\scenery_spider_web\env\lib\site-packages\pymysql\connections.py", line 549, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "d:\scenery_spider_web\env\lib\site-packages\pymysql\connections.py", line 779, in _read_query_result
    result.read()
  File "d:\scenery_spider_web\env\lib\site-packages\pymysql\connections.py", line 1157, in read
    first_packet = self.connection._read_packet()
  File "d:\scenery_spider_web\env\lib\site-packages\pymysql\connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "d:\scenery_spider_web\env\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "d:\scenery_spider_web\env\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'hunan_web.warehouse_spiderlog' doesn't exist")
```

**Comment by 0xAllenChen** [comment]
You need to look at point 3 of the README. The reason is that the table is not created

**Comment by shoukewei** [comment]
Great project. Thanks. It seems the problem `source ./data_bak/hunan_web_2023-05-12.sql`. Everything is fine when using `source ./new_hunan_web.sql`

**Comment by 0xAllenChen** [comment]
Thanks you for find the problem, I will edit README.
